language: java
jdk: openjdk8
install: true
cache:
  directories:
  - $HOME/.m2
script: 
  - jdk_switcher use openjdk8
  - mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V 
